# Generated by Django 4.2 on 2024-09-20 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xlsx_translation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadfile',
            name='file',
            field=models.FileField(default=None, max_length=250, null=True, upload_to='uploads/'),
        ),
    ]
