# Generated by Django 4.2 on 2024-09-20 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('xlsx_translation', '0002_alter_uploadfile_file'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UploadFile',
        ),
    ]
