# Generated by Django 4.2 on 2024-09-20 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xlsx_translation', '0004_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('image', models.ImageField(upload_to='dogs/')),
            ],
        ),
        migrations.DeleteModel(
            name='UploadFileModel',
        ),
    ]
