# Generated by Django 4.2 on 2024-09-20 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xlsx_translation', '0005_dog_delete_uploadfilemodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dog',
            name='image',
        ),
        migrations.AddField(
            model_name='dog',
            name='file',
            field=models.FileField(default='No files', upload_to='excel/'),
        ),
    ]
