# Generated by Django 4.2 on 2024-09-22 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('xlsx_translation', '0006_remove_dog_image_dog_file'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Dog',
            new_name='UploadModel',
        ),
    ]
