# Generated by Django 4.2 on 2024-09-24 05:06

from django.db import migrations, models
import xlsx_translation.models


class Migration(migrations.Migration):

    dependencies = [
        ('xlsx_translation', '0007_rename_dog_uploadmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadmodel',
            name='file',
            field=models.FileField(default='No files', upload_to='excel/', validators=[xlsx_translation.models.validate_file_extension]),
        ),
    ]
