# Generated by Django 4.2 on 2024-09-24 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xlsx_translation', '0008_alter_uploadmodel_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadmodel',
            name='file',
            field=models.FileField(default='No files', upload_to='excel/'),
        ),
    ]
